[table-settings]
table_view_mode = rich
max_table_rows_simple = 200
max_table_rows_rich = inf

[render-settings]
plot_dpi = 200
plot_default_figsize_in = 12,6
plot_bbox_tight = true
plot_pad_inches = 0.10

[ui-settings]
; header_text = "Test app"
; favicon = "www/free-png.png"
; page_title = "The Test App"
; logo = "www/free-png.png"

[view-order-settings]
sections =
    polars
    pandas
    plotnine

labels.plotnine =
    MEM-USED
    CPU%%